//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8793
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlimpSet.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OlimpSet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot; encoding=&quot;windows-1251&quot;/&gt;
        ///  
        ///  &lt;!--Весь документ--&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:text&gt;{\rtf\ansi\ansicpg1251 {\fonttbl{\f0 Arial;}}\f0\fs20&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\paperw11906\paperh16838&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\margl567\margr567\margt567\margb567&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;{\qc\fs32\b Список участников}\par&amp;#10;&lt;/xsl:text [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ListMap {
            get {
                return ResourceManager.GetString("ListMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot; encoding=&quot;windows-1251&quot;/&gt;
        ///  
        ///  &lt;!--Весь документ--&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:text&gt;{\rtf\ansi\ansicpg1251 {\fonttbl{\f0 Arial;}}\f0\fs24&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\paperh11906\paperw16838\landscape&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\margl567\margr567\margt567\margb567&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:for-each select=&quot;/OlimpSet/RoomList/Room&quot;&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RoomList {
            get {
                return ResourceManager.GetString("RoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot; encoding=&quot;windows-1251&quot;/&gt;
        ///  
        ///  &lt;!--Весь документ--&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:text&gt;{\rtf\ansi\ansicpg1251 {\fonttbl{\f0 Arial;}}\f0\fs24&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\paperh11906\paperw16838\landscape&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:text&gt;\margl567\margr567\margt567\margb567&amp;#10;&lt;/xsl:text&gt;
        ///    &lt;xsl:for-each select=&quot;/OlimpSet/RoomList/Room&quot;&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RoomMap {
            get {
                return ResourceManager.GetString("RoomMap", resourceCulture);
            }
        }
    }
}
